In [ ]:
# winequality-red.csv 파일의 데이터를 읽어서 테이블에 저장
# 1. 데이터베이스는 _2.ipynb에서 만든 data_repo 사용
# 2. 테이블 만들기 (red_wine)
# 3. 데이터 읽어서 red_wine 테이블에 저장
# 4. 7등급 이상의 데이터를 조회해서 파일로 저장 (high-quality-red-wine.csv)

In [1]:
import pymysql
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
try:
    conn = pymysql.connect(
        host= "127.0.0.1",
        user="humanda5",
        password="humanda5",
        database="data_repo"
    )
    
    cursor= conn.cursor()

    sql = """ create table if not exists red_wine
         ( 
              idx int primary key auto_increment,
              fixed_acidity float not null,
              volatile_acidity float not null,
              citric_acid float not null,
              residual_sugar float not null,
              chlorides float not null,
              free_sulfur_dioxide float not null,
              total_sulfur_dioxide float not null,
              density float not null,
              pH float not null,
              sulphates float not null,
              alcohol float not null,
              quality int not null
         )"""
    cursor.execute(sql)

except Exception as e:
    print("오류발생 : ", e)
finally:

    if cursor:
        cursor.close()
    if conn:    
        conn.close()

In [12]:
df_red_wine = pd.read_csv("data-files/winequality-red.csv", sep=";")

try:
    conn = pymysql.connect(
        host= "127.0.0.1",
        user="humanda5",
        password="humanda5",
        database="data_repo"
    )

    cursor = conn.cursor()

    # 명령 실행
    sql = "delete from red_wine"
    cursor.execute(sql)

    sql = """insert into red_wine 
             (fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol, quality)
             values 
             (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""

    data = df_red_wine.values.tolist()
    cursor.executemany(sql, data)
    conn.commit()

except Exception as e:
    print("오류발생 : ", e)
    if conn:
        conn.rollback()

finally:
    if cursor:
        cursor.close()
    if conn:    
        conn.close()

In [13]:
df_red_wine.head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5

In [1]:
try:
    conn = pymysql.connect(
        host= "127.0.0.1",
        user="humanda5",
        password="humanda5",
        database="data_repo"
    )
    cursor = conn.cursor()

    sql = """select * from red_wine where quality >= %s"""
    cursor.execute(sql, [7])
    red_wine_data = cursor.fetchall()

    df_red_wine = pd.DataFrame(red_wine_data, 
                           columns=['idx','fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'])
    df_red_wine.drop(['idx'], axis=1, inplace=True)
    df_red_wine.to_csv('data-files/high-quality-red-wine.csv', index=False)

except Exception as e:
    print("오류발생 : ", e)
finally:
    if cursor:
        cursor.close()
    if conn:    
        conn.close()

오류발생 :  name 'pymysql' is not defined

NameError: name 'cursor' is not defined